### ISSUE TITLE
"Method not found: UnityEngine.Vector3" After updating Unity to 6.3

### ISSUE THREAD

**Issue by laniakeadev** [Demigiant/dotween#718]
After I updated Unity to 6.3, with the last version of DoTween, the same message adds up to console every second:

```
MissingMethodException: Method not found: UnityEngine.Vector3 UnityEngine.Vector3.op_Subtraction(UnityEngine.Vector3,UnityEngine.Vector3)
DG.Tweening.Tweener.DoStartup[T1,T2,TPlugOptions] (DG.Tweening.Core.TweenerCore`3[T1,T2,TPlugOptions] t) (at D:/DG/_Develop/__UNITY_ASSETS/_Demigiant/__DOTween/_DOTween.Assembly/DOTween/Tweener.cs:163)
DG.Tweening.Core.TweenerCore`3[T1,T2,TPlugOptions].Startup () (at D:/DG/_Develop/__UNITY_ASSETS/_Demigiant/__DOTween/_DOTween.Assembly/DOTween/Core/TweenerCore.cs:250)
DG.Tweening.Core.TweenManager.ForceInit (DG.Tweening.Tween t, System.Boolean isSequenced) (at D:/DG/_Develop/__UNITY_ASSETS/_Demigiant/__DOTween/_DOTween.Assembly/DOTween/Core/TweenManager.cs:780)
DG.Tweening.Sequence.ApplyInternalCycle (DG.Tweening.Sequence s, System.Single fromPos, System.Single toPos, DG.Tweening.Core.Enums.UpdateMode updateMode, System.Boolean useInverse, System.Boolean prevPosIsInverse, System.Boolean multiCycleStep) (at D:/DG/_Develop/__UNITY_ASSETS/_Demigiant/__DOTween/_DOTween.Assembly/DOTween/Sequence.cs:363)
DG.Tweening.Sequence.DoApplyTween (DG.Tweening.Sequence s, System.Single prevPosition, System.Int32 prevCompletedLoops, System.Int32 newCompletedSteps, System.Boolean useInversePosition, DG.Tweening.Core.Enums.UpdateMode updateMode) (at D:/DG/_Develop/__UNITY_ASSETS/_Demigiant/__DOTween/_DOTween.Assembly/DOTween/Sequence.cs:252)
DG.Tweening.Sequence.ApplyTween (System.Single prevPosition, System.Int32 prevCompletedLoops, System.Int32 newCompletedSteps, System.Boolean useInversePosition, DG.Tweening.Core.Enums.UpdateMode updateMode, DG.Tweening.Core.Enums.UpdateNotice updateNotice) (at D:/DG/_Develop/__UNITY_ASSETS/_Demigiant/__DOTween/_DOTween.Assembly/DOTween/Sequence.cs:166)
DG.Tweening.Tween.DoGoto (DG.Tweening.Tween t, System.Single toPosition, System.Int32 toCompletedLoops, DG.Tweening.Core.Enums.UpdateMode updateMode) (at D:/DG/_Develop/__UNITY_ASSETS/_Demigiant/__DOTween/_DOTween.Assembly/DOTween/Tween.cs:266)
DG.Tweening.Core.TweenManager.Update (DG.Tweening.Tween t, System.Single deltaTime, System.Single independentTime, System.Boolean isSingleTweenManualUpdate) (at D:/DG/_Develop/__UNITY_ASSETS/_Demigiant/__DOTween/_DOTween.Assembly/DOTween/Core/TweenManager.cs:596)
DG.Tweening.Core.TweenManager.Update (DG.Tweening.UpdateType updateType, System.Single deltaTime, System.Single independentTime) (at D:/DG/_Develop/__UNITY_ASSETS/_Demigiant/__DOTween/_DOTween.Assembly/DOTween/Core/TweenManager.cs:444)
DG.Tweening.Core.DOTweenComponent.Update () (at D:/DG/_Develop/__UNITY_ASSETS/_Demigiant/__DOTween/_DOTween.Assembly/DOTween/Core/DOTweenComponent.cs:75)

```

**Comment by Demigiant** [comment]
Ahoy!

I'm investigating this right now. It seems an issue on their side with broken APIs in Unity beta (sometimes they do that with betas), where they broke operators when they added the missing multiplication/division ones for Vector3, but I'll know more in a few hours. Thanks for the warning.

**Comment by manowargoblin** [comment]
+1 for this too.
I upgraded to 6.3 and got the same error. Can't go back to 6.2 as Unity broke the particle system with a memory leak.
If you could provide a temp workaround on DoTween I'd be grateful.

**Comment by Demigiant** [comment]
It's a little complicated because the broken API have a cascade effect on other things, but I hope to have a workaround after the weekend, maybe even Sunday

**Comment by Demigiant** [comment]
Done, you can download the fixed DOTween libraries [here](http://dotween.demigiant.com/tmp/DOTween_1_2_785_Unity6_3beta.zip). I tested them and I'm not getting any errors anymore, but let me know.

P.S. If you're using DOTween Pro let me know because that requires a separate update

**Comment by manowargoblin** [comment]
I'm trying to use the libraries you provided by 
1) Importing (from the asset store) DoTween from the package manager.
2) I get the compile error about Vector3
3) I copy your libraries to my project F:\Unity Projects\BoB\Assets\Plugins\Demigiant\DOTween
4) But Unity 6.3b tries to compile these (when I go into your Setup panel) and is missing the Core & Plugins
Assets\Plugins\Demigiant\DOTween\Modules\DOTweenModuleSprite.cs(7,19): error CS0234: The type or namespace name 'Core' does not exist in the namespace 'DG.Tweening' (are you missing an assembly reference?)
Assets\Plugins\Demigiant\DOTween\Modules\DOTweenModuleSprite.cs(8,19): error CS0234: The type or namespace name 'Plugins' does not exist in the namespace 'DG.Tweening' (are you missing an assembly reference?)
Assets\Plugins\Demigiant\DOTween\Modules\DOTweenModuleUnityVersion.cs(318,22): error CS0246: The type or namespace name 'Tween' could not be found (are you missing a using directive or an assembly reference?)
etc 

What's the correct way to get the amended files in your zip file into my project?

**Comment by laniakeadev** [comment]
> Done, you can download the fixed DOTween libraries [here](http://dotween.demigiant.com/tmp/DOTween_1_2_785_Unity6_3beta.zip). I tested them and I'm not getting any errors anymore, but let me know.
> 
> P.S. If you're using DOTween Pro let me know because that requires a separate update

Thanks, everything works fine for me after update.

**Comment by Demigiant** [comment]
@manowargoblin You should simply overwrite the DOTween folder with the one inside the ZIP (it's a full replacement, you can even delete the DOTween folder and replace it with the one in the ZIP). Is it possible that you unzipped it inside the DOTween folder, so that you got a "Demigiant/DOTween/DOTween" subfolder and double the files?

@laniakeadev Yay! ^_^

**Comment by manowargoblin** [comment]
@Demigiant It was missing DemLib folder. Putting that back solved the compile.
Thx - all working (compiling) now in Unity 6.3b. Hopefully they fix the Vector3 soon anyway, but thx for the excellent support.
regards

**Comment by mryilanc1** [comment]
Dotween Pro working  on Unity 6.0 and 6.2

But it doesn't work on Unity 6.3.0b3

I need Dotween Pro for Unity 6.3 

if you edited it, please share us

I can show the Invoice

@Demigiant

**Comment by Demigiant** [comment]
Hi @mryilanc1, please write me (via [this contact form](https://demigiant.com/about.php#contactWrap) or via the email indicated in the Asset Store) so I can share the Pro update with you privately (please consider that I'm out these days, but I should be back during the weekend, Monday max)

**Comment by OSGPierre** [comment]
The errors still occur in 6000.3.0b6, b7 and b8, should we expect an official fix from Unity or from Demigiant?
That problem doesn't seem to affect other plugins like Magica Cloth, Tail Animator, Ferr2D, Odin Inspector, FMOD, Febucci Text Animator.

@Demigiant

**Comment by Demigiant** [comment]
Ahoy. I'm waiting for 6.3 to be out of beta, because beta versions are sometimes a mess and Unity has hinted (but I don't know if that will happen) that they will solve it on their side. In the meantime, while I haven't put the fix on the Asset Store (because I don't want it to break if they fix it with 6.3 final) I have uploaded it to DOTween's website, [under the main download button](https://dotween.demigiant.com/download.php#download).

**Comment by Demigiant** [comment]
Closing this: Unity 6.3b10 (and the official 6.3.0f1) fixed this problem on Unity's side
