### ISSUE TITLE
UWP Build Error

### ISSUE THREAD

**Issue by OzoneABN** [Demigiant/dotween#303]
> **Thanks**!, it solved it completely!:)
> Unity 2018 | UWP (Hololens) | .NET 4.x | DOTween v1.2.235
> 
> The demon appeared for me with the face of:
> " The name 'AppDomain' does not exist in the current context... "

Hello,
Using DOTween 1.2.235 will cause the " The name 'AppDomain' does not exist in the current context... "
build error inside Unity (2018.3.12f1). Trying to exclude the corresponding lines in DOTweenModuleUtilities.cs (line 56+) from build using

    [UnityEngine.Scripting.Preserve]
        // Just used to preserve methods when building, never called
        static void Preserver()
        {
    #if !WINDOWS_UWP
            Assembly[] loadedAssemblies = AppDomain.CurrentDomain.GetAssemblies();
            MethodInfo mi = typeof(MonoBehaviour).GetMethod("Stub");
    #endif
        }

will fix the build-problem inside Unity, but when trying to build it forHoloLens with VS the same error occurs again (but somewere else).

Downgrading to DOTween 1.1.710 solved this error for me.
Will there be an fix in a newer version of DOTween anytime soon?
 Regards

_Originally posted by @OzoneABN in https://github.com/Demigiant/dotween/issues/257#issuecomment-481245700_

**Comment by Demigiant** [comment]
Ahoy,

I did actually solve this bug by implementing the `Preserve` attribute for those lines, which are indeed fundamental, and after that users could build on HoloLens without problems. It's very weird that it resurfaced for you. Can you un-comment those and tell me more about your build settings?

**Comment by Morgan-6Freedom** [comment]
Same issue when Trying to build with Unity 2018.3.13f1 + Dotween 1.2.245 + Holotoolkit

`Assets\Plugins\DOTween\Modules\DOTweenModuleUtils.cs(60,43): error CS0103: The name 'AppDomain' does not exist in the current context
`

![image](https://user-images.githubusercontent.com/49686866/57682232-9eba5f00-7631-11e9-9a1d-714f78f420e1.png)

**Comment by Morgan-6Freedom** [comment]
The build show no error with Dotween 1.1.710

**Comment by StarBax89** [comment]
Same error with DoTween 1.2.250 in Unity 2018.4.0f1

**Comment by Demigiant** [comment]
Hi, on what Unity version and configuration are you? Can you check [this link](https://docs.microsoft.com/en-us/windows/uwp/gaming/missing-dot-net-apis-in-unity-and-uwp#scripting-backend-configuration) to see if it helps, since it appears that your configuration doesn't support Reflection?

**Comment by StarBax89** [comment]
Hi, here is my config. Unity 2018.4.0.f1
![Unbenannt](https://user-images.githubusercontent.com/9252776/58931302-85539100-875f-11e9-9663-af48e661ea2b.PNG)
![Unbenannt2](https://user-images.githubusercontent.com/9252776/58931303-85539100-875f-11e9-94f9-201540dd4b02.PNG)
